# Generated by Django 5.1.4 on 2026-09-03 06:02

from django.db import migrations, models


def adopt_numbers_already_on_file(apps, schema_editor):
    """Carry across whatever is already in contact_details, where it parses.

    That field has always been the de facto phone number — free text, never
    validated — so the numbers are mostly there already and asking six people
    to retype what the system can read is a poor first impression of a new
    feature.

    Conservative on purpose: anything that does not parse as a Philippine
    mobile is left exactly where it is, and contact_details is never cleared.
    Nothing is marked verified — parsing a number proves it is well formed,
    not that the person holding this account can receive at it.
    """
    from accounts.phone import normalise_ph_mobile, InvalidPhilippineMobile

    User = apps.get_model("accounts", "User")
    adopted = 0
    for user in User.objects.exclude(contact_details="").iterator():
        try:
            number = normalise_ph_mobile(user.contact_details)
        except InvalidPhilippineMobile:
            continue        # a landline, an extension, a note — leave it
        if number:
            user.phone = number
            user.save(update_fields=["phone"])
            adopted += 1
    if adopted:
        print(f"    adopted {adopted} number(s) from contact_details")


def forget_them(apps, schema_editor):
    """Reversing the migration drops the column anyway; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(adopt_numbers_already_on_file, forget_them),
    ]
