# Generated by Django 5.1.4 on 2026-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_email_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "office_address",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "contact_details",
                    models.TextField(blank=True, default="", max_length=300),
                ),
                (
                    "head_of_office_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "head_of_office_title",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tbl_agency_profile",
            },
        ),
    ]
