# Generated by Django 5.1.4 on 2026-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_agency_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="license_valid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
