# Generated by Django 5.1.4 on 2026-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0010_selfreportflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologicalreport",
            name="check_findings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="psychologicalreport",
            name="check_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
