# Generated by Django 5.1.4 on 2026-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_drop_ai_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("archived", "Archived"),
                    ("login", "Login"),
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("withdrawn", "Withdrawn"),
                ],
                max_length=20,
            ),
        ),
    ]
