# Generated by Django 5.1.4 on 2026-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_case_study_final_reopen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("archived", "Archived"),
                    ("login", "Login"),
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("withdrawn", "Withdrawn"),
                    ("finalized", "Finalized"),
                    ("reopened", "Reopened"),
                    ("removed", "Removed"),
                ],
                max_length=20,
            ),
        ),
    ]
