# Generated by Django 5.1.4 on 2026-09-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_unavailability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("session_count", models.PositiveSmallIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_session_reminder",
                "ordering": ["-day", "psychologist_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("psychologist", "day"),
                        name="one_session_reminder_per_day",
                    )
                ],
            },
        ),
    ]
