# Generated by Django 5.1.4 on 2026-09-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_session_reminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustodianReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custodian_reminder",
                        to="scheduling.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_custodian_reminder",
            },
        ),
    ]
