# Generated by Django 5.1.4 on 2026-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0026_assignment_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminationrecord",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("Reunified with family", "Reunified with family"),
                    ("Adoption finalized", "Adoption finalized"),
                    ("Transferred to another agency", "Transferred to another agency"),
                    ("Aged out of program", "Aged out of program"),
                    ("Services completed", "Services completed"),
                    ("Other", "Other"),
                    ("Counseling completed", "Counseling completed"),
                    (
                        "Favorable pre-assessment, no counseling needed",
                        "Favorable pre-assessment, no counseling needed",
                    ),
                    (
                        "Pre-assessment only, evaluation completed",
                        "Pre-assessment only, evaluation completed",
                    ),
                    ("Counseling discontinued", "Counseling discontinued"),
                    (
                        "Referred to another specialist or service",
                        "Referred to another specialist or service",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
