# Generated by Django 5.1.4 on 2026-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0028_custodian"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="alias",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="child",
            name="health_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Healthy", "Healthy"),
                    ("With special needs", "With special needs"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="special_needs",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="child",
            name="birth_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Marital", "Marital"),
                    ("Non-Marital", "Non-Marital"),
                    ("Child", "Child"),
                    ("Unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="type_of_adoption",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regular", "Regular"),
                    ("Domestic Relative", "Domestic Relative"),
                    (
                        "Relative (Without 2-yr custody)",
                        "Relative (Without 2-yr custody)",
                    ),
                    ("Step-parent", "Step-parent"),
                    ("Adult", "Adult"),
                    ("SIBRA", "SIBRA"),
                    ("ICA Relative", "ICA Relative"),
                    ("IP", "IP"),
                    ("Foster-Adopt", "Foster-Adopt"),
                ],
                max_length=50,
            ),
        ),
    ]
