# Generated by Django 5.1.4 on 2026-10-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0029_scsr_identifying_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="legal_status_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
