# Generated by Django 5.1.4 on 2026-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0030_legal_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="intake_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
