# Generated by Django 5.1.4 on 2026-10-04 15:15

"""Record whose child's record the model read, and attribute the rows already
logged.

A brief names the child, but a summary names its document and the self-report
check its survey. Existing rows are attributed from what still exists. A
summary whose document was deleted before this ran cannot be traced and stays
null.
"""
import django.db.models.deletion
from django.db import migrations, models


def attribute(apps, schema_editor):
    """Fill `child` on the brief, summary and self-report rows from input_ref.

    Only those three job types: a chat row's input_ref is typed text and could
    look like "child:12". Kept self-contained - a migration must keep meaning
    what it meant when it ran, whatever the app code becomes.
    """
    AssistantJob = apps.get_model("assistant", "AssistantJob")
    Child = apps.get_model("children", "Child")
    PsychologicalReport = apps.get_model("clinical", "PsychologicalReport")
    CaseReferral = apps.get_model("clinical", "CaseReferral")
    OpinionnaireInvite = apps.get_model("clinical", "OpinionnaireInvite")

    child_of = {
        "child": {pk: pk for pk in Child.objects.values_list("id", flat=True)},
        "report": dict(PsychologicalReport.objects.values_list("id", "child_id")),
        "casereferral": dict(CaseReferral.objects.values_list("id", "child_id")),
        "invite": dict(OpinionnaireInvite.objects.values_list("id", "child_id")),
    }
    batch = []
    for job in (AssistantJob.objects
                .filter(job_type__in=("brief", "doc_intelligence", "self_report"),
                        child__isnull=True)
                .only("id", "input_ref").iterator()):
        prefix, _, pk = job.input_ref.partition(":")
        child_id = child_of.get(prefix, {}).get(int(pk)) if pk.isdigit() else None
        if not child_id:
            continue
        job.child_id = child_id
        batch.append(job)
        if len(batch) >= 500:
            AssistantJob.objects.bulk_update(batch, ["child"])
            batch = []
    if batch:
        AssistantJob.objects.bulk_update(batch, ["child"])


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0005_assistantjob_answer_result_count"),
        ("children", "0028_custodian"),
        # The backfill reads the report, referral and survey tables.
        ("clinical", "0011_report_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantjob",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_jobs",
                to="children.child",
            ),
        ),
        # Reversing drops the column, which takes the attribution with it.
        migrations.RunPython(attribute, migrations.RunPython.noop),
    ]
