# Generated by Django 5.1.4 on 2026-10-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0006_assistantjob_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantjob",
            name="prompt_sha",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="assistantjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("brief", "Pre-Session Brief"),
                    ("doc_intelligence", "Document Summary"),
                    ("remark_polish", "Remark Polishing"),
                    ("census_narrative", "Census Narrative"),
                    ("chat", "Chatbot Question"),
                    ("self_report", "Self-Report Check"),
                    ("case_brief", "Case Brief"),
                ],
                max_length=30,
            ),
        ),
    ]
