# Generated by Django 5.1.4 on 2026-09-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('owner_role', models.CharField(max_length=60)),
                ('target_days', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_adoption_stage',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=160)),
                ('owned_externally', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_templates', to='adoption.adoptionstage')),
            ],
            options={
                'db_table': 'tbl_adoption_requirement_template',
                'ordering': ['stage__number', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'code'), name='uniq_requirement_code_per_stage')],
            },
        ),
    ]
