# Generated by Django 5.1.4 on 2026-09-09 00:53

import adoption.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
        ('children', '0018_remove_child_guardian_delete_guardian'),
        ('clinical', '0010_selfreportflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('cea_number', models.CharField(blank=True, max_length=60)),
                ('cea_expiry', models.DateField(blank=True, null=True)),
                ('home_study_expiry', models.DateField(blank=True, null=True)),
                ('children_in_household', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('matched', 'Matched'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='eligible', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_adoption_pap',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, choices=[('Adoption finalized', 'Adoption finalized'), ('Placement disruption', 'Placement disruption'), ('Reunified with biological family', 'Reunified with biological family'), ('Aged out', 'Aged out'), ('Referred out of RACCO I', 'Referred out of RACCO I')], max_length=60)),
                ('closure_note', models.TextField(blank=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_cases', to='children.child')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='adoption.adoptionstage')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_cases_owned', to=settings.AUTH_USER_MODEL)),
                ('pap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='adoption.pap')),
            ],
            options={
                'db_table': 'tbl_adoption_case',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=160)),
                ('started_at', models.DateField()),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('satisfied_at', models.DateField(blank=True, null=True)),
                ('extension_days', models.PositiveSmallIntegerField(default=0)),
                ('extension_document', models.FileField(blank=True, null=True, upload_to=adoption.models.requirement_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clocks', to='adoption.adoptioncase')),
            ],
            options={
                'db_table': 'tbl_adoption_clock',
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_handoffs', to='children.child')),
                ('pre_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_handoffs', to='clinical.preassessment')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_handoffs_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_adoption_handoff',
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('advance', 'Advance'), ('revert', 'Revert')], default='advance', max_length=10)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_stage_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='adoption.adoptioncase')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='adoption.adoptionstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='adoption.adoptionstage')),
            ],
            options={
                'db_table': 'tbl_adoption_stage_event',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=160)),
                ('owned_externally', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('waived', 'Waived')], default='pending', max_length=12)),
                ('document', models.FileField(blank=True, null=True, upload_to=adoption.models.requirement_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='adoption.adoptioncase')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='adoption.adoptionstage')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requirements_submitted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requirements_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_adoption_requirement',
                'ordering': ['stage__number', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('case', 'stage', 'code'), name='uniq_requirement_per_case_stage')],
            },
        ),
    ]
